### ISSUE TITLE
Can't deploy this project to now

### ISSUE THREAD

**Issue by jeblister** [hanpama/next-with-antd#1]
Here is the message error 
```
Using "webpack" config function defined in next.config.js.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 137
> npm ERR! next-with-antd@1.0.0 build: `next build`
> npm ERR! Exit status 137
> npm ERR! 
> npm ERR! Failed at the next-with-antd@1.0.0 build script.
```

**Comment by hanpama** [comment]
I can build this on local machine without errors.And now deployment still throws errors. I'm using next.js without now, so I have no understanding about differences between local and now environment.

**Comment by jeblister** [comment]
I solved this issue by using this [nextjs-starter](https://github.com/soulmachine/nextjs-starter-kit).

This problem is due to the issue that Next.js can only import CSS using styled-jsx or CSS-in-JS built in with jsx syntax and Next.js is not able to use css-loader. See the warning from official page https://github.com/zeit/next.js/#customizing-webpack-config:

> Warning: Adding loaders to support new file types (css, less, svg, etc.) is not recommended because only the client code gets bundled via webpack and thus it won't work on the initial server rendering. Babel plugins are a good alternative because they're applied consistently between server/client rendering
