### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by piuccio** [hanpama/next-with-antd#2]
Hey thanks for the project, great works. You can further reduce the output bundle size by adding this to your `.babelrc`

```
"plugins": [
    [
      "import",
      {
        "libraryName": "antd"
      }
    ]
  ],
```

And of course you need the extra dependency https://github.com/ant-design/babel-plugin-import

**Comment by hanpama** [comment]
Thank you for your help @piuccio . Now the bundle size of `index.js` file is 868KB (in dev mode)! It was originally 9.4MB
