### ISSUE TITLE
Less

### ISSUE THREAD

**Issue by justinmoon** [hanpama/next-with-antd#6]
I see that you're importing the compiled and minified CSS from antd. This makes it hard to customize antd using LESS.

Have you looked into including a LESS compiler?

**Comment by hanpama** [comment]
I have tried in some ways but couldn’t find a good option 😅 

The official example is helpful but I think it is not very customizable.
https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less

Currently I’m going to keep this boilerplate in css.😊
